kaspad_address: "kaspad:16110"

block_wait_time: 1000
print_stats: true
log_to_file: false

health_check_port: ""
web_dashboard_port: ":3030"

var_diff: true
shares_per_min: 30
var_diff_stats: true
pow2_clamp: true

extranonce_size: 2
coinbase_tag_suffix: "Kraskus Solo"

instances:
  - stratum_port: ":5556"
    min_share_diff: 512
    prom_port: ""
    log_to_file: false
