services:
  app_proxy:
    environment:
      APP_HOST: portal
      APP_PORT: 80

  portal:
    image: nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10
    restart: unless-stopped
    volumes:
    - ./portal:/usr/share/nginx/html:ro
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ${APP_DATA_DIR}/data/status:/status:ro
    security_opt:
    - no-new-privileges:true
    ports:
    - 0.0.0.0:33060:80
    extra_hosts:
    - host.docker.internal:host-gateway
    depends_on:
    - update-agent

  mysterium:
    image: mysteriumnetwork/myst:1.39.5-alpine@sha256:d0c270c6bcb50c1004ba355c264f85aa16b3a5a414f8b9f8f5b0f449ea85a142
    restart: unless-stopped
    network_mode: host
    cap_add:
    - NET_ADMIN
    command:
    - service
    - --agreed-terms-and-conditions
    volumes:
    - ${APP_DATA_DIR}/data/mysterium:/var/lib/mysterium-node

  nodeui-proxy:
    image: nginx:1.27-alpine@sha256:65645c7bb6a0661892a8b03b89d0743208a18dd2f3f17a54ef4b76fb8e2f2a10
    restart: unless-stopped
    network_mode: host
    volumes:
    - ${APP_DATA_DIR}/data/nodeui-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
    security_opt:
    - no-new-privileges:true
    depends_on:
    - mysterium

  status-agent:
    image: alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
    restart: unless-stopped
    network_mode: host
    environment:
      APP_VERSION: 2.6.5
      NODE_VERSION: 1.39.5
      STATUS_INTERVAL: '30'
    command:
    - /bin/sh
    - /opt/status-agent/status.sh
    volumes:
    - ${APP_DATA_DIR}/data/status-agent:/opt/status-agent:ro
    - /proc:/host-proc:ro
    - /sys:/host-sys:ro
    - /:/host-root:ro
    - ${APP_DATA_DIR}/data/mysterium:/mysterium-data:ro
    - ${APP_DATA_DIR}/data/status:/status
    security_opt:
    - no-new-privileges:true
    depends_on:
    - mysterium

  update-agent:
    image: docker:29.6.2-cli-alpine3.24@sha256:be132a9f282288de4afaf63379dff75711fda0147c6b72a9df44e51841402144
    restart: unless-stopped
    environment:
      APP_DIR: /app
      APP_DATA_DIR: ${APP_DATA_DIR}
      UPDATE_DIR: /update
      UPDATE_CHECK_INTERVAL: '21600'
      MYST_SERVICE: mysterium
    command:
    - /bin/sh
    - /opt/updater/serve.sh
    volumes:
    - ${APP_DATA_DIR}/data/updater:/opt/updater:ro
    - .:/app
    - /var/run/docker.sock:/var/run/docker.sock
    - ${APP_DATA_DIR}:${APP_DATA_DIR}
    - ${APP_DATA_DIR}/data/update:/update
    tmpfs:
    - /tmp
    security_opt:
    - no-new-privileges:true
    depends_on:
    - mysterium
